server:
  port: 8090

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: usuario-service
              uri: http://usuario-service:8080
              predicates:
                - Path=/usuarios/**

            - id: skins-service
              uri: http://skins-service:8081
              predicates:
                - Path=/skins/**

            - id: compra-service
              uri: http://compra-service:8082
              predicates:
                - Path=/compras/**

            - id: carrito-service
              uri: http://carrito-service:8083
              predicates:
                - Path=/carrito/**

            - id: inventario-service
              uri: http://inventario-service:8084
              predicates:
                - Path=/inventario/**

            - id: pagos-service
              uri: http://pagos-service:8085
              predicates:
                - Path=/pagos/**

            - id: favoritos-service
              uri: http://favoritos-service:8086
              predicates:
                - Path=/favoritos/**

            - id: reviews-service
              uri: http://reviews-service:8087
              predicates:
                - Path=/reviews/**

            - id: notificaciones-service
              uri: http://notificaciones-service:8088
              predicates:
                - Path=/notificaciones/**

            - id: wishlist-service
              uri: http://wishlist-service:8089
              predicates:
                - Path=/wishlist/**