spring.application.name=notificaciones-service

spring.datasource.url=jdbc:mysql://mysql:3306/notificaciones_db
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8088